import DES
import str_work
print("Предложение:")
print(str_work.hex_string("ДВОРЯК"))
print("")
print("Ключ:")
print(str_work.hex_string("ДИАНА"))
print("-" * 128)
P = str_work.binary_string("ДВОРЯК")
print("Бинарный вид предложения:")
print(P)
P = "0" * (len(DES.STANDART_PERMUTATION) - len(P)) + P
print("Расширение предложения до 64-х бит:")
print(P)
P = str_work.str_permutation(P, DES.STANDART_PERMUTATION)
print("Стандартная перестановка:")
print(P)
print("-" * 128)
print("Бинарный вид ключа:")
K = str_work.binary_string("ДИАНА")
print(K)
print("Расширение ключа:")
K = "0" * (64 - len(K)) + K
print(K)
C = DES.DES_E(K, P)
print("Зашифрованное сообщение выглядит так:")
print(C)
